version: '3'
    
services:
    db:
      image: postgres
      restart: unless-stopped
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=password
      command: python manage.py migrate
    web:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      depends_on:
        - db